[supervisord]
nodaemon=true
user=root

[program:uvicorn]
command=uvicorn approvals:app --host 0.0.0.0 --port 8000
directory=/
autostart=true
autorestart=False
stdout_logfile=/var/log/uvicorn_stdout.log
stderr_logfile=/var/log/uvicorn_stderr.log

[program:dependabotalerts]
command=python3 /dependabotalerts_scheduling.py
directory=/
autostart=true
autorestart=true
stdout_logfile=/var/log/dependabotalerts_out.log
stderr_logfile=/var/log/dependabotalerts_err.log