[supervisord]
nodaemon=true

[program:uvicorn]
command=uvicorn approvals:app --host 0.0.0.0 --port 8000
directory=/
autostart=true
autorestart=False

[program:dependabotalerts]
command=python3 /dependabotalerts_scheduling.py
directory=/
autostart=true
autorestart=true